// http file to test the format of the API requests

### Create a new user
POST http://localhost:3001/api/sessions/register
Content-Type: application/json

{
    "name":"Magnificent",
    "surname":"Manager",
    "role":"manager",
    "username":"manager2",
    "password":"manager@123"

}

### Login
POST http://localhost:3001/api/sessions/login
Content-Type: application/json

{
    "username":"manager1",
    "password":"manager@123"
}   

### Check current user
GET http://localhost:3001/api/sessions/current

### Logout
DELETE http://localhost:3001/api/sessions/logout

### Get a ticket
POST http://localhost:3001/api/service/ticket
Content-Type: application/json

{
    "service":"shipping and RECEIVING"
}

### Get a ticket 
POST http://localhost:3001/api/service/ticket
Content-Type: application/json

{
    "service":"MONEY TRANSFER"
}

### Get a ticket
POST http://localhost:3001/api/service/ticket
Content-Type: application/json

{
    "service":"public service"
}

### Call next customer
POST http://localhost:3001/api/service/ticket/next HTTP/1.1
Content-Type: application/json

{
    "date": "2024-03-19"
}

### Clear queues
DELETE http://localhost:3001/api/service/resetQueues